version: "2"

services:
  web:
    environment:
      - COMPOSE_HTTP_TIMEOUT=1000
    stdin_open: true
    tty: true
    build: .
    hostname: notesapp
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/notesapp
      - bundle:/bundle
    links:
      - db
  db:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=notesapp
volumes:
  bundle: