version: "2"

services:
  web:
    build: .
    hostname: railsapp
    command: bundle exec rails s -p 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/railsapp
      - bundle:/bundle
    links:
      - db
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=notesapp
volumes:
  bundle: